In [4]:
#Numpy -is a linear algebra library for python. It can be used to generate data.

# numpy also works with multodimentional array

import numpy as np

In [5]:
mylist = [1,2,3,4,5]
type(mylist)

list

In [6]:
x = np.array(mylist)
x

array([1, 2, 3, 4, 5])

In [7]:
type(x)

numpy.ndarray

In [8]:
#numpy array are faster than python list

data = [[1,2,3],[4,5,6],[7,8,9]]
data

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
record = np.array(data)
record

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# generating data with numpy
#arange()- generates a rage of positive numbers

np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [26]:
# generating evenly spaced numbers

np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [34]:
# generating random numbers
# rand generates floating random numbers greater than 0 and less than 1

np.random.rand(5,4)

array([[0.18145937, 0.6071255 , 0.87491427, 0.4457913 ],
       [0.37642381, 0.28173599, 0.67015592, 0.73215936],
       [0.27621002, 0.10266892, 0.35970845, 0.61503102],
       [0.33091414, 0.98812049, 0.35758065, 0.75262096],
       [0.04680428, 0.92925968, 0.04183205, 0.65620903]])

In [36]:

# randn will generate random numbers that can be less than 0 ad greater than 1

np.random.randn(10,3)

array([[ 1.15631688,  0.62851029,  0.66886903],
       [ 0.06447527, -0.06008207,  0.98914073],
       [ 1.48772614,  0.61155951,  0.16391145],
       [-0.54751858,  0.42651269, -1.35281942],
       [ 1.371798  , -0.7501307 ,  0.90500011],
       [-0.52102369, -0.92833986,  0.63616265],
       [ 0.28358335, -1.09462993, -0.72264466],
       [-1.92953261, -0.80718093,  0.11401006],
       [-0.47455877, -0.17410677, -0.66135552],
       [-0.43517338, -0.89913029, -1.50000541]])

In [43]:
np.random.randint(1,4,24).reshape(6,4)

array([[2, 2, 3, 2],
       [2, 3, 3, 3],
       [2, 1, 1, 2],
       [1, 3, 1, 2],
       [1, 3, 1, 2],
       [1, 2, 2, 1]])

In [44]:
# indexing numpy array

x = np.arange(1,26).reshape(5,5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [52]:
x[3][0]

16

In [62]:
# Slicing numpy array

x[4][3:5]

array([24, 25])

In [75]:
x[2:4,1:3]

array([[12, 13],
       [17, 18]])

In [82]:
x[1:3,0:2]

array([[ 6,  7],
       [11, 12]])

In [83]:
# arithmetic with python list
mylist + mylist

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [84]:
np.array(mylist) + np.array(mylist)

array([ 2,  4,  6,  8, 10])

In [85]:
np.array(mylist)

array([1, 2, 3, 4, 5])

In [88]:
# broadcasting
np.arange(1,10).reshape(3,3) + np.arange(1,4)

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [90]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
np.arange(1,4)

array([1, 2, 3])

In [92]:
np.arange(1,10).reshape(3,3) + np.arange(1,2)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [94]:
np.arange(1,3)

array([1, 2])

In [93]:
np.arange(1,10).reshape(3,3) + 7

array([[ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16]])

In [95]:
np.arange(1,7).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.arange(1,19).reshape(3,6)+np.arange(1,7.reshape)

In [96]:
x.sum()

325

In [97]:
#sum items by column

x.sum(axis=0)


array([55, 60, 65, 70, 75])

In [102]:
# sum items by row

x.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [103]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [104]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [107]:
use .seed()to freeze the random state of your values
np.random.seed(5)
y= np.random.randint(1,10,5)
y

array([4, 7, 7, 1, 9])

In [108]:
x


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [109]:
comparison operator in numpy

x > 10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [ ]:
# Pandas - Python library for data analysis

# series and dataframe
#series - single column
#dataframe- multiple columns

In [110]:
sample = np.arange(1,11)
sample

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
import pandas as pd

In [113]:
sample = pd.Series(sample)
sample

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int32

In [114]:
sample[8]

9

In [117]:
df = np.random.randint(100,500,12).reshape(4,3)
df

array([[485, 310, 203],
       [244, 105, 414],
       [356, 488, 210],
       [264, 461, 279]])

In [120]:


df = pd.DataFrame(data=df, columns=["Jan","Feb","Mar"], index=["MTN","UBA","CNN","JUMIA"])
df

Jan  Feb  Mar
MTN    485  310  203
UBA    244  105  414
CNN    356  488  210
JUMIA  264  461  279

In [122]:
df.to_csv("demo.csv")

In [124]:
# importing data in pandas

df = pd.read_html("https://en.wikipedia.org/wiki/The_World%27s_Billionaires")
df[2]


No.                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   
5    6                Bill Gates    $104 billion   67  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   

          Primary source(s) of wealth  
0                                LVMH  
1                       Tesla, SpaceX  
2                              Amazon  
3                  Oracle Corporation  
4                  Berkshire Hathaway  
5                           Microsoft  
6                      Bloomberg L.P.  
7  Telmex, América Móvil, Grupo Carso  
8                 Reliance Industries  
9                           Microsoft

In [125]:
# Exploratory data analysis (EDA)
# check rows and columns

df[2].shape

(10, 6)

In [126]:
df = df[2]

In [127]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   No.                          10 non-null     int64 
 1   Name                         10 non-null     object
 2   Net worth (USD)              10 non-null     object
 3   Age                          10 non-null     int64 
 4   Nationality                  10 non-null     object
 5   Primary source(s) of wealth  10 non-null     object
dtypes: int64(2), object(4)
memory usage: 608.0+ bytes


In [128]:
df.describe()

No.        Age
count  10.00000  10.000000
mean    5.50000  71.700000
std     3.02765  12.247902
min     1.00000  51.000000
25%     3.25000  65.500000
50%     5.50000  70.500000
75%     7.75000  80.250000
max    10.00000  92.000000

In [131]:
Asssessing 

df["Name"]

0    Bernard Arnault & family
1                   Elon Musk
2                  Jeff Bezos
3               Larry Ellison
4              Warren Buffett
5                  Bill Gates
6           Michael Bloomberg
7        Carlos Slim & family
8               Mukesh Ambani
9               Steve Ballmer
Name: Name, dtype: object

In [139]:
df[["Name","Age", "Net worth (USD)"]]

Name  Age Net worth (USD)
0  Bernard Arnault & family   74    $211 billion
1                 Elon Musk   51    $180 billion
2                Jeff Bezos   59    $114 billion
3             Larry Ellison   78    $107 billion
4            Warren Buffett   92    $106 billion
5                Bill Gates   67    $104 billion
6         Michael Bloomberg   81   $94.5 billion
7      Carlos Slim & family   83     $93 billion
8             Mukesh Ambani   65   $83.4 billion
9             Steve Ballmer   67   $80.7 billion

In [140]:
# REMOVING A COLUM
df.drop("Age", axis=1)


No.                      Name Net worth (USD)    Nationality  \
0    1  Bernard Arnault & family    $211 billion         France   
1    2                 Elon Musk    $180 billion  United States   
2    3                Jeff Bezos    $114 billion  United States   
3    4             Larry Ellison    $107 billion  United States   
4    5            Warren Buffett    $106 billion  United States   
5    6                Bill Gates    $104 billion  United States   
6    7         Michael Bloomberg   $94.5 billion  United States   
7    8      Carlos Slim & family     $93 billion         Mexico   
8    9             Mukesh Ambani   $83.4 billion          India   
9   10             Steve Ballmer   $80.7 billion  United States   

          Primary source(s) of wealth  
0                                LVMH  
1                       Tesla, SpaceX  
2                              Amazon  
3                  Oracle Corporation  
4                  Berkshire Hathaway  
5                           Microsoft  
6                      Bloomberg L.P.  
7  Telmex, América Móvil, Grupo Carso  
8                 Reliance Industries  
9                           Microsoft

In [141]:
df

No.                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   
5    6                Bill Gates    $104 billion   67  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   

          Primary source(s) of wealth  
0                                LVMH  
1                       Tesla, SpaceX  
2                              Amazon  
3                  Oracle Corporation  
4                  Berkshire Hathaway  
5                           Microsoft  
6                      Bloomberg L.P.  
7  Telmex, América Móvil, Grupo Carso  
8                 Reliance Industries  
9                           Microsoft

In [147]:
# removing multiple column
df.drop(["Age","Natioality"], [axis =1)

SyntaxError: invalid syntax (4025134387.py, line 2)

In [146]:
#adding a new colum

df["Double Age"] = df["Age"] *2
df

No.                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   
5    6                Bill Gates    $104 billion   67  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   

          Primary source(s) of wealth  Double Age  
0                                LVMH         148  
1                       Tesla, SpaceX         102  
2                              Amazon         118  
3                  Oracle Corporation         156  
4                  Berkshire Hathaway         184  
5                           Microsoft         134  
6                      Bloomberg L.P.         162  
7  Telmex, América Móvil, Grupo Carso         166  
8                 Reliance Industries         130  
9                           Microsoft         134

In [148]:
# Renaming column

df.columns

Index(['No.', 'Name', 'Net worth (USD)', 'Age', 'Nationality',
       'Primary source(s) of wealth', 'Double Age'],
      dtype='object')

In [149]:
df.rename(columns={"No.":"S/N"})

S/N                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   
5    6                Bill Gates    $104 billion   67  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   

          Primary source(s) of wealth  Double Age  
0                                LVMH         148  
1                       Tesla, SpaceX         102  
2                              Amazon         118  
3                  Oracle Corporation         156  
4                  Berkshire Hathaway         184  
5                           Microsoft         134  
6                      Bloomberg L.P.         162  
7  Telmex, América Móvil, Grupo Carso         166  
8                 Reliance Industries         130  
9                           Microsoft         134

In [155]:
# accessing rows and multiple rows

df.iloc[1:5]

No.            Name Net worth (USD)  Age    Nationality  \
1    2       Elon Musk    $180 billion   51  United States   
2    3      Jeff Bezos    $114 billion   59  United States   
3    4   Larry Ellison    $107 billion   78  United States   
4    5  Warren Buffett    $106 billion   92  United States   

  Primary source(s) of wealth  Double Age  
1               Tesla, SpaceX         102  
2                      Amazon         118  
3          Oracle Corporation         156  
4          Berkshire Hathaway         184

In [156]:
#dropping a row
df.drop(1,axis=0)

No.                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   
5    6                Bill Gates    $104 billion   67  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   

          Primary source(s) of wealth  Double Age  
0                                LVMH         148  
2                              Amazon         118  
3                  Oracle Corporation         156  
4                  Berkshire Hathaway         184  
5                           Microsoft         134  
6                      Bloomberg L.P.         162  
7  Telmex, América Móvil, Grupo Carso         166  
8                 Reliance Industries         130  
9                           Microsoft         134

In [157]:
df.append(df)

C:\Users\ihett\AppData\Local\Temp\ipykernel_4308\443893503.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append(df)


No.                      Name Net worth (USD)  Age    Nationality  \
0    1  Bernard Arnault & family    $211 billion   74         France   
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   
5    6                Bill Gates    $104 billion   67  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   
0    1  Bernard Arnault & family    $211 billion   74         France   
1    2                 Elon Musk    $180 billion   51  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
3    4             Larry Ellison    $107 billion   78  United States   
4    5            Warren Buffett    $106 billion   92  United States   
5    6                Bill Gates    $104 billion   67  United States   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
8    9             Mukesh Ambani   $83.4 billion   65          India   
9   10             Steve Ballmer   $80.7 billion   67  United States   

          Primary source(s) of wealth  Double Age  
0                                LVMH         148  
1                       Tesla, SpaceX         102  
2                              Amazon         118  
3                  Oracle Corporation         156  
4                  Berkshire Hathaway         184  
5                           Microsoft         134  
6                      Bloomberg L.P.         162  
7  Telmex, América Móvil, Grupo Carso         166  
8                 Reliance Industries         130  
9                           Microsoft         134  
0                                LVMH         148  
1                       Tesla, SpaceX         102  
2                              Amazon         118  
3                  Oracle Corporation         156  
4                  Berkshire Hathaway         184  
5                           Microsoft         134  
6                      Bloomberg L.P.         162  
7  Telmex, América Móvil, Grupo Carso         166  
8                 Reliance Industries         130  
9                           Microsoft         134

In [158]:
#insert multiple rows

df.append(df,ignore_index=True)

C:\Users\ihett\AppData\Local\Temp\ipykernel_4308\1863409504.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append(df,ignore_index=True)


No.                      Name Net worth (USD)  Age    Nationality  \
0     1  Bernard Arnault & family    $211 billion   74         France   
1     2                 Elon Musk    $180 billion   51  United States   
2     3                Jeff Bezos    $114 billion   59  United States   
3     4             Larry Ellison    $107 billion   78  United States   
4     5            Warren Buffett    $106 billion   92  United States   
5     6                Bill Gates    $104 billion   67  United States   
6     7         Michael Bloomberg   $94.5 billion   81  United States   
7     8      Carlos Slim & family     $93 billion   83         Mexico   
8     9             Mukesh Ambani   $83.4 billion   65          India   
9    10             Steve Ballmer   $80.7 billion   67  United States   
10    1  Bernard Arnault & family    $211 billion   74         France   
11    2                 Elon Musk    $180 billion   51  United States   
12    3                Jeff Bezos    $114 billion   59  United States   
13    4             Larry Ellison    $107 billion   78  United States   
14    5            Warren Buffett    $106 billion   92  United States   
15    6                Bill Gates    $104 billion   67  United States   
16    7         Michael Bloomberg   $94.5 billion   81  United States   
17    8      Carlos Slim & family     $93 billion   83         Mexico   
18    9             Mukesh Ambani   $83.4 billion   65          India   
19   10             Steve Ballmer   $80.7 billion   67  United States   

           Primary source(s) of wealth  Double Age  
0                                 LVMH         148  
1                        Tesla, SpaceX         102  
2                               Amazon         118  
3                   Oracle Corporation         156  
4                   Berkshire Hathaway         184  
5                            Microsoft         134  
6                       Bloomberg L.P.         162  
7   Telmex, América Móvil, Grupo Carso         166  
8                  Reliance Industries         130  
9                            Microsoft         134  
10                                LVMH         148  
11                       Tesla, SpaceX         102  
12                              Amazon         118  
13                  Oracle Corporation         156  
14                  Berkshire Hathaway         184  
15                           Microsoft         134  
16                      Bloomberg L.P.         162  
17  Telmex, América Móvil, Grupo Carso         166  
18                 Reliance Industries         130  
19                           Microsoft         134

In [161]:
# sorting data
df.sort_values(by="Name",ascending=False)

No.                      Name Net worth (USD)  Age    Nationality  \
4    5            Warren Buffett    $106 billion   92  United States   
9   10             Steve Ballmer   $80.7 billion   67  United States   
8    9             Mukesh Ambani   $83.4 billion   65          India   
6    7         Michael Bloomberg   $94.5 billion   81  United States   
3    4             Larry Ellison    $107 billion   78  United States   
2    3                Jeff Bezos    $114 billion   59  United States   
1    2                 Elon Musk    $180 billion   51  United States   
7    8      Carlos Slim & family     $93 billion   83         Mexico   
5    6                Bill Gates    $104 billion   67  United States   
0    1  Bernard Arnault & family    $211 billion   74         France   

          Primary source(s) of wealth  Double Age  
4                  Berkshire Hathaway         184  
9                           Microsoft         134  
8                 Reliance Industries         130  
6                      Bloomberg L.P.         162  
3                  Oracle Corporation         156  
2                              Amazon         118  
1                       Tesla, SpaceX         102  
7  Telmex, América Móvil, Grupo Carso         166  
5                           Microsoft         134  
0                                LVMH         148

In [162]:
# filtering your data

df["Age"]>60

0     True
1    False
2    False
3     True
4     True
5     True
6     True
7     True
8     True
9     True
Name: Age, dtype: bool

In [163]:
df["Nationality"]!="United States"

0     True
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8     True
9    False
Name: Nationality, dtype: bool

In [189]:
df[(df["Nationality"] != "United States")& (df["Age"])]

TypeError: list indices must be integers or slices, not str

In [190]:
df[df["Nationality"].isin(["India","Mexico"])]

TypeError: list indices must be integers or slices, not str

In [191]:
#useful functions
def firstname(x):
    return x.split()[0]


In [192]:
firstname("Elon Musk")

'Elon'

In [193]:
df["firstname"] = df["Name"].apply(firstname)
df

TypeError: list indices must be integers or slices, not str

In [194]:
def Lastname(x)
    return x.split()[1]

SyntaxError: invalid syntax (4168220559.py, line 1)

In [195]:
# first five rows
df.head()

AttributeError: 'list' object has no attribute 'head'

In [196]:
#last 5  rows
df.tail()

AttributeError: 'list' object has no attribute 'tail'

In [188]:
df.value_counts("Nationality")

AttributeError: 'list' object has no attribute 'value_counts'

In [197]:
df["Nationality"].unique()

TypeError: list indices must be integers or slices, not str

In [198]:
df["Nationality"].nunique()

TypeError: list indices must be integers or slices, not str

In [199]:
# top 3 billionaire
df.head(3)

AttributeError: 'list' object has no attribute 'head'